spring.application.name=amazon-service-registry

server.port=8761

server.servlet.context-path=/registry

# Stopping eureka for self registration as a client.
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false


eureka.client.service-url.defaultZone=http://localhost:8761/registry/eureka/