spring.application.name=payment-service


#spring.jpa.hibernate.ddl-auto=create

server.port=8003
server.servlet.context-path=/payment

spring.profiles.active=dev

spring.config.import=optional:configserver:http://localhost:9999/configserver/

