spring.application.name=order-service

#spring.jpa.hibernate.ddl-auto=create

server.port=8002
server.servlet.context-path=/order

spring.config.import=optional:configserver:http://localhost:9999/configserver


