spring.application.name=amazon-config-server

server.port=9999
server.servlet.context-path=/configserver

spring.cloud.config.server.git.uri=https://github.com/surajsrivastav044/amazon-config-data.git
#spring.cloud.config.server.git.default-label=master