spring.application.name=amazon-api-gateway

server.port=8080

#Note: As we are implementing service registry to do the routing configuration dynamically so it is not required now I am commening for future reference
##Micro Service routing
##Context path, port number
#
##For user
#spring.cloud.gateway.server.webmvc.routes[0].id=user-service
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8001
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**
#
##For order
#spring.cloud.gateway.server.webmvc.routes[1].id=order-service
#spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8002
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/order/**
#
##For payment
#spring.cloud.gateway.server.webmvc.routes[2].id=payment-service
#spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8003
#spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/payment/**

#Adding eureka server url
eureka.client.service-url.defaultZone=http://localhost:8761/registry/eureka/

#enabling discovery routing

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

