# db properties configuration
datasource.url=jdbc:mysql://sit-db-localhost:3306/collage
datasource.username=root
datasource.password=Hello@321
.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

contact.email=sit@gmail.com